apiVersion: v1
kind: Template
labels:
  template: create-3scale-tenant
metadata:
  annotations:
    description: Template to create a 3scale tenant
    tags: 3scale-tenant
    version: 1.0.0
  name: create-3scale-tenant
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${TENANT_USERNAME}-secret
    namespace: ${TARGET_NAMESPACE}
  stringData:
    admin_password: ${TENANT_PASSWORD}
  type: Opaque
- kind: Tenant
  apiVersion: capabilities.3scale.net/v1alpha1
  metadata:
    name: ${TENANT_USERNAME}
    namespace: ${TARGET_NAMESPACE}
  spec:
    username: ${TENANT_USERNAME}
    systemMasterUrl: ${SYSTEM_MASTER_URL}
    email: ${TENANT_EMAIL}
    organizationName: ${TENANT_ORG}
    masterCredentialsRef:
      name: system-seed
      namespace: ${SYSTEM_MASTER_NAMESPACE}
    passwordCredentialsRef:
      name: ${TENANT_USERNAME}-secret
      namespace: ${TARGET_NAMESPACE}
    tenantSecretRef:
      name: tenant-token-secret
      namespace: ${TARGET_NAMESPACE}
parameters:
- description: Tenant username
  name: TENANT_USERNAME
  required: true
- description: Tenant password
  name: TENANT_PASSWORD
  required: true
- description: Tenant email
  name: TENANT_EMAIL
  required: true
- description: Tenant organization
  name: TENANT_ORG
  required: true
- description: Target namespace
  name: TARGET_NAMESPACE
  required: true
- description: System master URL
  name: SYSTEM_MASTER_URL
  required: true
- description: System master namespace
  name: SYSTEM_MASTER_NAMESPACE
  required: true
