apiVersion: v1
kind: Template
labels:
  template: role-binding-template
metadata:
  annotations:
    version: 0.1.0
  name: role-binding-template
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      template: jenkins
    name: jenkins_edit
    namespace: ${APP_NAMESPACE}
  roleRef:
    name: ${ROLE}
  subjects:
  - kind: ServiceAccount
    name: ${SA_NAME}
    namespace: ${SA_NAMESPACE}
  userNames:
  - system:serviceaccount:${SA_NAMESPACE}:${SA_NAME}
parameters:
- description: The namespace to deploy into
  name: APP_NAMESPACE
  required: true
- description: Name of a service account that can deploy to this project
  name: SA_NAME
  required: true
  value: jenkins
- description: Namespace of service account that can deploy to this project
  name: SA_NAMESPACE
  required: true
  value: 3scale-apimanager
- description: role
  name: ROLE
  value: edit
